language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

matrix:
  allow_failures:
    - python: "2.5"
    - python: "3.2"
    - python: "3.3"

# command to install dependencies
#install:
#  - "pip install . --use-mirrors"
#  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests
